export const Productlist = [
  {
    id: 1,
    name: "amazon speaker",
    detail: "Lorem ipsum dolor sit amet",
    price: "2599",
    hero: "OMG This just came out today!",
    quantity:"0",
    totalPrice:"0",
    image: "1.jpg",
  },
  {
    id: 2,
    name: "Smart Watch",
    detail: "Lorem ipsum dolor sit amet",
    price: "4499",
    info: "This is the latest and greatest product from Derp corp.",
    quantity:"0",
    totalPrice:"0",
    image: "2.jpg",
  },
  {
    id: 3,
    name: "Headphones",
    detail: "Lorem ipsum dolor sit amet",
    price: "2399",
    offer: "BOGOF",
    quantity:"0",
    totalPrice:"0",
    image: "3.jpg",
  },
  {
    id: 4,
    name: "Shoes",
    detail: "Lorem ipsum dolor sit amet",
    price: "899",
    quantity:"0",
    totalPrice:"0",
    image: "4.jpg",
  },
  {
    id: 5,
    name: "Sunglasses",
    detail: "Lorem ipsum dolor sit amet",
    price: "1599",
    offer: "No srsly GTFO",
    quantity:"0",
    totalPrice:"0",
    image: "5.jpg",
  },
  {
    id: 6,
    name: "Smartwatch Pro",
    detail: "Lorem ipsum dolor sit amet",
    price: "11999",
    quantity:"0",
    totalPrice:"0",
    image: "6.jpg",
  },
  {
    id: 7,
    name: "Bottle",
    detail: "Lorem ipsum dolor sit amet",
    price: "999",
    info: "This is the latest and greatest product from Derp corp.",
    offer: "info with offer",
    quantity:"0",
    totalPrice:"0",
    image: "7.jpg",
  },
];
